### ISSUE TITLE
Easier user customization

### ISSUE THREAD

**Issue by Lenbok** [belak/emacs-monokai-pro-theme#2]
I use an after-load-theme-hook to set/alter some extra faces that monokai doesn't define, however it is quite difficult to use the palette that monokai defines in a nice manner, at least compared to the same customizations made to zenburn, e.g.:

```lisp
(defun customize-zenburn ()
    "Customize zenburn theme"
    (if (member 'zenburn custom-enabled-themes)
        (zenburn-with-color-variables
          (custom-theme-set-faces
           'zenburn
           `(show-paren-match ((t (:background ,zenburn-bg+05 :weight bold))))
           ))))
  (add-hook 'after-load-theme-hook 'customize-zenburn)
```
Note that the zenburn colors names are made available via the zenburn-with-color-variables macro https://github.com/bbatsov/zenburn-emacs/blob/af63b09069d731f46c0ba38f2f578162e2dcb0d5/zenburn-theme.el#L156-L167 (and it also lets the user set `zenburn-override-colors-alist` if they want to adjust some of the colors)

```lisp
(defun customize-monokai ()
    "Customize monokai theme"
    (if (member 'monokai-pro custom-enabled-themes)
        (custom-theme-set-faces
         'monokai-pro
         `(show-paren-match ((t (:background "#a9dc76" :weight bold))))
         )))
  (add-hook 'after-load-theme-hook 'customize-monokai)
```
With monokai I have to manually put the colors in rather than by reference to the names. Can you add similar capabilities to monokai please?

**Comment by belak** [comment]
There are actually some tools already in here you can use! There's a small DSL I use for defining my themes, so you may want to use that rather than the direct custom-theme-set-faces. This will automatically replace any of the named colors in the theme alist with their actual values.

```
(monokai-pro-theme-set-faces
 'monokai-pro
  monokai-pro-theme-colors
  '(
     (face-name :background blue)
   )
)
```

That should at least put you on the right track! If you're looking for something more than this, I can try taking another look, but I'm pretty sure this is exactly what you were looking for.
